### ISSUE TITLE
Switch to libGDX?

### ISSUE THREAD

**Issue by matys18** [matys18/Inda-project#10]
As @macaullyjames mentioned in issue #8, there might be some dragons around. Switching to libGDX (or some other engine) might be a good idea. What do you think @Jarlius?

**Comment by Jarlius** [comment]
Sure, but let's hope setting it up and reading tutorials don't delay us too much. It definitely will make the game more polished, but the point of keeping it in JFrame was to have it super-simple, and delivering on time?
It might prove a good challenge though.

**Comment by matys18** [comment]
It will be harder to set up and to get started, but hopefully we can get some of that time back by not having to write our own colliders and other stuff. I think it's a good idea

**Comment by Jarlius** [comment]
Alright I'll start and look how to set it up with eclipse and then read on key bindings

**Comment by matys18** [comment]
Cool, I'll create a ligGDX desktop project and push it to the repo

**Comment by macaullyjames** [comment]
Awesome stuff. [pqbyte/coherence](https://github.com/pqbyte/coherence) uses libGDX as well, you might be able to help each other get off the ground faster :)

**Comment by matys18** [comment]
We have migrated
