### ISSUE TITLE
Come up with a name

### ISSUE THREAD

**Issue by matys18** [matys18/Inda-project#11]
Our cool game needs a cool name :smile: 

We should work on that :thought_balloon:

**Comment by Jarlius** [comment]
Hm... some wordplay on Shadow and Labyrinth perhaps?
Darkyrinth?
Also you use emotes with colons? :zap: (test) oo nice

**Comment by Jarlius** [comment]
How about,
Mazescape?
You know, Maze and Escape in one word?

**Comment by macaullyjames** [comment]
The only thing harder than this is deciding how you'll spend all your millions after launch 🤔💰

**Comment by matys18** [comment]
I like Mazescape 👍  Shall we go with that?

**Comment by Jarlius** [comment]
Yeah let's do that :smile:

**Comment by matys18** [comment]
Name has been changed
