### ISSUE TITLE
Game Music

### ISSUE THREAD

**Issue by matys18** [matys18/Inda-project#15]
Our game should have some music. Since we don't want an army of lawyers going after us, we need something that is royalty-free. I was thinking some old, creepy piano music. What do you think @Jarlius?

**Comment by macaullyjames** [comment]
This SE question might be of interest: [Where can I find free music for my game?](http://gamedev.stackexchange.com/questions/14/where-can-i-find-free-music-for-my-game).

**Comment by Jarlius** [comment]
Any music should do, for now, it's just a file so it's easy to change.
But sure, creepy would maybe increase the jumpscares which makes for an overall better game or so youtube have told me

**Comment by matys18** [comment]
I'll work on adding some ambient sounds and some creepy music! 👍

**Comment by matys18** [comment]
The game now has ambient music and collision sounds! 🔊 

The ambient music is my edit of _Music for Strings, Percussion and Celesta, III_ by _Béla Bartók_ who died over 70 years ago, meaning that his work is copyright-free. The collision sounds are simple piano chords from Garage Band. 😄

**Comment by macaullyjames** [comment]
Just a heads up: The 70 year rule applies to the release date of the recording in this case, not the day the composer died ([more info](https://www.gov.uk/government/publications/copyright-in-sound-recordings/copyright-in-sound-recordings)). Make sure you're in compliance 🤓👌🏻

**Comment by matys18** [comment]
@macaullyjames Are you sure it's like that in Sweden? I was under the impression that based on Swedish law, it's life + 70 years.

 We're still good by both measures 👍

**Comment by macaullyjames** [comment]
The copyright for the composition (i.e. the notes in the song) expires 70 years after the author's death but the copyright for the audio recording expires 70 years after release. Think of it this way: Shakespeare died a long time ago so anyone can use his works for whatever but it's still illegal to pirate the Romeo + Juliet movie. I'm pretty sure it's the same across the E.U.

Not that it matters anyway in your case 😛

**Comment by matys18** [comment]
@macaullyjames Damn... I was really looking forward to watching Romeo & Juliet tonight... Oh well 😞

**Comment by macaullyjames** [comment]
IT'S SO SAD!!! 😭😭😭

**Comment by Jarlius** [comment]
The current sounds are really good! :+1: The collision sounds fit nicely too
