### ISSUE TITLE
Menu implementation

### ISSUE THREAD

**Issue by Jarlius** [matys18/Inda-project#16]
Writing the UserInput class gave me a few ideas, but I wonder, is it worth bothering turning off rendering while in menu-mode? As frames will only update on cue whenever the user navigates the menu (and turn it back on whenever the user starts/resumes game)

**Comment by matys18** [comment]
That's a great idea, as long as we don't have any background animations in the menu 👍

**Comment by Jarlius** [comment]
Good, I'll keep this issue open for further menu development

**Comment by matys18** [comment]
No longer relevant since we switched to libGDX.
