### ISSUE TITLE
Abstract Screen superclass, and names

### ISSUE THREAD

**Issue by Jarlius** [matys18/Inda-project#20]
I'm starting to see some similarities between Screen classes.
They will all have their own Control object, which they pass to UserInput when shown. They will also most likely share Screen size, etc.
How about refactoring, and creating a Screen superclass?
What name should we give it - Screen being taken? Perhaps AbScreen, or SuperScreen?
Or maybe GameScreen, and change the current GameScreen to MazeScreen?
Oh and maybe also changing main Game class from sample MyGdxGame to MazeGame?

**Comment by matys18** [comment]
**Names:** In 6690ad92217bf3861d89acfe70d4e325ec0c6e04 the main class has been renamed `MyGdxGame.java` --> `Mazescape.java` 👍  Just pull from the develop branch

**Screen Superclass:** Could you explain a bit more? 😇  I don't think I quite get what you want to change

**Comment by matys18** [comment]
Ok never mind, i see what you did there, that works 👍

**Comment by matys18** [comment]
I think you have already implemented this ❓ Don't forget to close issues that have been addressed 👍
