### ISSUE TITLE
Attach UI controller to PlayerModel

### ISSUE THREAD

**Issue by matys18** [matys18/Inda-project#21]
I have finally implemented a suitable, controllable `PlayerModel` into the `GameScreen`. 😄  This means that it's now time to attach the user-input controller that you wrote before.

This is how the `PlayerModel` works: It uses box2d physics to move itself around the world. Since it is a "physical" object it's not supposed to move by setting it's (x,y) coordinates, but rather by setting it's velocity. You can set the velocity by calling the `setVelocity(Vector2 v)` method on the player object in the `GameScreen` class. This is how it should look like:

Key pressed ⬆️  --> player.setVelocity(new Vector2(0, 40))
Key released ⬆️  --> player.setVelocity(new Vector2(0, 0))

So eassentialy you're passing the (x, y) velocity(speed) as a `Vector2` to the `setVelocity(Vector2 v)` method. 🔬 

Could you please update your input classes so that they perform the actions above? 😇

**Comment by Jarlius** [comment]
Done!

The arrow keys should now be more resilient to spam, too. Feel free to mash them keys :hammer: and the `PlayerModel` will still behave properly!

**Comment by matys18** [comment]
Nice, works really well!
