### ISSUE TITLE
Add Game Title to Menu

### ISSUE THREAD

**Issue by matys18** [matys18/Inda-project#22]
Our menu could use a title! Could you add some big text at the centre-top that reads "Mazescape"? 😄

**Comment by Jarlius** [comment]
Added and centered it, but the current title is very ugly... :disappointed: 
Not sure on how to add better texture

**Comment by matys18** [comment]
Look into [FreeType](https://github.com/libgdx/libgdx/wiki/Gdx-freetype) which we already have as a dependency in our project. It should enable you to draw smooth text, and select a font as well! 🎉  Aside from the fonts on your computer, you can find other fonts [here](https://www.fontsquirrel.com/). 

I was also thinking, maybe it looks better when it's not centered? I thought it would be better at the centre, but now I'm not sure anymore, maybe we should put it to the right and have some animations on the left instead? What do you think?

PS: The font files should go in the `assets/fonts` folder 👍

**Comment by Jarlius** [comment]
Done, tough there are many different fonts to choose from.
But yes, something at the left would be real nice

**Comment by matys18** [comment]
Haha that spooky skeleton, good job 😄
