### ISSUE TITLE
Make menu do stuff

### ISSUE THREAD

**Issue by matys18** [matys18/Inda-project#25]
We have a very nice looking menu, good job @Jarlius! 🎉  Unfortunately it does not do anything at the moment. Could you make the "new game" button start a new game, and the "exit" button close the game completely? 😇

**Comment by Jarlius** [comment]
Yeah, "New Game" only resumes the game at the moment..

Wait, "exit" doesn't work for you? It does for me :confounded:
Are you pressing spacebar when a word his highlighted?

Options should be the only one not working, as I'm not too sure what options to add..

**Comment by Jarlius** [comment]
Oops closed by mistake

**Comment by matys18** [comment]
Oh... My bad. I was pressing enter all along instead of space 😖 Could you make enter do the same thing space does? 😇

**Comment by Jarlius** [comment]
Yup, added it now :balloon:
