### ISSUE TITLE
Come up with a character, and a backstory

### ISSUE THREAD

**Issue by matys18** [matys18/Inda-project#27]
So now we have an orange blob wandering around a maze... Great! But wait...  who is the blob anyways? Why is the blob in the maze? So many questions, and not a lot of answers... 😖 

It is also worth noting that the blob can be very easily switched with a sprite, so the sky is the limit when it comes to who the blob could potentially be. Old grumpy man? A cute kitten? Manbearpig? Hmm... 💭 

Any ideas @Jarlius? 😄

**Comment by Jarlius** [comment]
I'm kind of liking the idea of a yellow blob. Did you play Thomas was Alone? If not then it's a platformer where the player rectangle is "Thomas", who then finds other rectangle friends and they help each other reach higher places.

Perhaps the yellow blob is looking for his/her sibling, who's gone dark? And maybe let the "goal" be to bring light back to the black blob? :black_circle: 

And maybe better names than [color] blob :name_badge:

**Comment by matys18** [comment]
Sure that sounds cool, for the names we could just call the by their color. Ex: "This is Yellow and he is a blob". The blackblob idea is also cool!

I was thinking, instead of the score system, maybe we should have the light become smaller and smaler over time, and when it goes completely dark you loose? Then we could fit this story in nicely

**Comment by Jarlius** [comment]
Yes! And maybe put out smaller dots on certain locations on the map - when picked up, they increase your lightlevel slightly. :bulb: 

And perhaps even let :black_circle: have a role in this! The :black_circle: will hunt you, and if caught, you'll lose some light?

Though that would lead back to original problem. How to win the game? Is it to gather all the lightdots á la Pacman? Reaching the "end" of the maze would be impossible if we implement the :snake: neverending screen idea.

There is a "chamber" like room opposite to where the player spawns in the current level. I originally thought maybe that's where :black_circle: will spawn, after a set amount of time and then hunt the player. But maybe let it be the goal, but blocked by a different colored wall `DoorWall` which requires keys to open it?

And when the player gathers all three keys you enter and win?

**Comment by matys18** [comment]
The keys might be much for now. I'll try to make the end area launch blobs of darkness at you though 😄

**Comment by matys18** [comment]
We pretty much have this down 👍  closing
