### ISSUE TITLE
Neverending Maze

### ISSUE THREAD

**Issue by Jarlius** [matys18/Inda-project#29]
How about a Snake-like screen? :snake: 

Reaching the end of the map would transport you to the other side.
Hopefully this would lead to more disorientation :dizzy: on the player.

**Comment by matys18** [comment]
Could be cool, but it could make the game very difficult. Lets hold this one back for now and decide a bit further down the line.

**Comment by Jarlius** [comment]
Yes, hence the "Super-cool stuff" milestone tag

**Comment by Jarlius** [comment]
While theoretically it seemed like an easy thing to implement, lots of fine-tuning was needed, as not to give any hints to the player of their location - fake walls, exact locations of teleports etc. But it turned out fairly smooth, except for one thing :beetle:  - but I'll create a separate bug issue for it.
