### ISSUE TITLE
Blackblob hunter

### ISSUE THREAD

**Issue by Jarlius** [matys18/Inda-project#30]
From the End room spawns a :black_circle: occasionally, which if reaches the player in a given amount of time steals some of the player's light.

**Comment by matys18** [comment]
Good idea!

**Comment by matys18** [comment]
I don't think we have time for this. I will make the light go out little by little for now.

**Comment by Jarlius** [comment]
Yes, it would require an AI and that'd be a project of its own

**Comment by Jarlius** [comment]
Hm did you implement the decaying light yet? It might just be me because I'm not seeing it, maybe I'm just impatient.
For testing the "loose" game feature, how do I make the decay timer faster?

**Comment by matys18** [comment]
Not yet, but the gameOver function will be called

**Comment by matys18** [comment]
Implemented as of 8e7a097bcb9fe7b3b8e2b7211eae0a81fc144993. 

The time is set to 3 minutes. 🕐
