### ISSUE TITLE
End goal room

### ISSUE THREAD

**Issue by Jarlius** [matys18/Inda-project#31]
The game must end somehow, and my current idea is that the end room is opposite to the player spawn, but must be reached by gathering keys :closed_lock_with_key: 

Maybe keys are too much of a bother to implement - if so we can hide the end room somewhere in the maze. But most important is to have an end room, of sorts.

The end room would have a circle, which if the lightblob steps in it,you win the game.

Where do we check if the lightblob is currently standing within the End Circle? In `render` method in `GameScreen`, or somewhere else?

**Comment by matys18** [comment]
Keys might be a bit much for now, but it's a decent idea. 

I can implement the end area! :thumbsup:

**Comment by matys18** [comment]
End area is now implemented 👍  @Jarlius please take a look at #41
