### ISSUE TITLE
Split code into packages

### ISSUE THREAD

**Issue by matys18** [matys18/Inda-project#33]
Right now we have a lot of different classes in the core directory. To improve readability and maintain a consistent structure it might be good to put all of the views(Screens) in one package and all of the controllers(Input classes) into another package, something like what we have with the Models and Levels. The problem is that when that is done, some variables become inaccessible. I'll work on this 👍

**Comment by Jarlius** [comment]
I added an example of how it's done just now, unless you figured it out already and are currently implementing it.

Basically, to share information between packages without importing stuff all the time, you can have different source folders, all containing the same package (`code`, for instance) and order the different groups of classes by their sourcefolders instead.

Or did you find another way of solving it?

**Comment by Jarlius** [comment]
I could do it also of course, not doing much at the moment :walking:

**Comment by Jarlius** [comment]
I took the freedom and made the changes :cold_sweat: I hope it was okay.

Close it if you don't feel there's more to change.

**Comment by Jarlius** [comment]
Wow, it wasn't as easy as I thought it'd be
Fixing it real quick

**Comment by matys18** [comment]
Packages (subpackages in this case) are the way to go. Make sure you use getters and setters for the package-private fields, don't make them public. 👍

**Comment by Jarlius** [comment]
I didn't, 

It should be working now, but the assets are messing it all up - Weren't they supposed to be located in core/assets? Perhaps when remaking the whole project I forgot to reinstall some plugin..

Edit: Yep I had just forgotten to set up Run Configurations to use assets. Closing now

**Comment by matys18** [comment]
Nice, looks good! I have a few very small suggestions, but we can talk about that at the övning tomorrow (13:00 in room 1537). 👍

**Comment by Jarlius** [comment]
Ok I'll see you then!
