### ISSUE TITLE
Level 1: Clear description, dont forget the details!

### ISSUE THREAD

**Issue by EricLewe** [matys18/Inda-project#35]
Liked project description, but could be good to clarify that gradlew build script is used (explain what is needed in order to make a gradlew script run maybe). Mention which language this is programmed in.

What is the goal of the project? To implement everything specified in the MvP? To have a sentence saying what the goal is could be a good thing.

What version of libgdx is used? Perhaps a brief explanation of it?

I really liked the authors file. 

Moreover perhaps explain game controls //maybe its explained in game

I find the project description clear, but it is because I think I know what this project is all about. So I guess by providing some meta text + the details regarding versions etc could make the description even clearer.

**Comment by matys18** [comment]
Thanks for the feedback! Your suggestions have been implemented in dbb7e75c690a683ab61fdcf7a785dca0a7f7734b! 😄
