### ISSUE TITLE
Level 3: Use of Milestones and Features in Issue Tracker

### ISSUE THREAD

**Issue by codewitchio** [matys18/Inda-project#36]
The issue tracker is used well, and it's easy to follow your communication and lines of thought. Milestones are clear are used properly, however I would like to see the priority of the different milestones somehow. Which milestones do you need to finish for your MVP? Which milestones do you think you'll manage even if they're not required for the MVP? Which milestones are more unrealistic and not something you'll work on except if you have lots of time to spare?

This could be conveyed in multiple ways, either you assign a priority in the title of the milestone (like P1: Visual Interface) or specified in the [README](README.md) where you specify the MVP.

**Comment by matys18** [comment]
Good suggestion! 👍  Thanks!
