### ISSUE TITLE
Level 4: Good bug reporting

### ISSUE THREAD

**Issue by EricLewe** [matys18/Inda-project#37]
Good flow in #28, specific with what happens.

Same goes for #32. Stating the obvious this issue could have been reported earlier according to jarlius reply. The details regarding what is causing the bug and also how the bug was resolved is very well explained.  Ideally please mention in which class file the bug is occurring. I found it good providing the exception type. Good job! :+1:

**Comment by matys18** [comment]
Thanks for the feedback!
