### ISSUE TITLE
Level 5: Use of Branching and Pull Requests

### ISSUE THREAD

**Issue by codewitchio** [matys18/Inda-project#38]
Two branches are used, `develop` for code in progress and `master` for finished code. This is often enough but _might_ lead to conflicts which can be more easily handled if you used issue- or feature-specific branches instead. Using new branches in combination with pull requests can make it easier to review eachother's code. However, all of this is preference and if it works for you there's no reason to change it.

**Comment by matys18** [comment]
Noted and understood. 👍  Thanks for the feedback!
