### ISSUE TITLE
Player Light flashes when teleporting

### ISSUE THREAD

**Issue by Jarlius** [matys18/Inda-project#39]
You'd think that the :snake: would eat the :bug: and the :beetle: and keep them pesky bugs away from the snake-like teleportation from edges of map, but apparently this is not the case.

The light flashes ever-so-slightly upon teleportation - indicating to the player that they've reached the end of map, which may give them more information than it should.

You now more about the :bulb: mechanics, so could you take a look at it @matys18 ?

**Comment by matys18** [comment]
I'll take a look 👍

**Comment by Jarlius** [comment]
Excellent work! :smiley:
