### ISSUE TITLE
Create a distributable copy of the game

### ISSUE THREAD

**Issue by matys18** [matys18/Inda-project#40]
We need a distributable version of the game for our technologically challenged friends to play. 

Will make one before Wednesday 👍

**Comment by macaullyjames** [comment]
GitHub can help you with this: https://help.github.com/articles/creating-releases/

**Comment by matys18** [comment]
[Done!](https://github.com/matys18/Mazescape/releases/tag/0.0.1) 

Thanks @macaullyjames for the advice!
