### ISSUE TITLE
Merge relic in AUTHORS

### ISSUE THREAD

**Issue by macaullyjames** [matys18/Inda-project#42]
The AUTHORS file looks a bit weird, looks like a merge went wrong somewhere ^^

``` diff
<<<<<<< HEAD
# Names should be added to this file like so:
# Name <email address>
# Keep the list alphabetically sorted.

# Authors

=======
# Names should be added to this file like so:
# Name <email address>
# Keep the list alphabetically sorted.

# Authors

Jarl Silvén <jarl.silven@gmail.com>
Matas Kairaitis <matas.kairaitis@gmail.com>
```

**Comment by matys18** [comment]
I have no idea what you're talking about 😇  9e73532b7cc743d5d0e725d1023987507f188175

**Comment by macaullyjames** [comment]
There's no escaping the truth 😉

<img width="756" alt="screen shot 2016-05-24 at 16 23 36" src="https://cloud.githubusercontent.com/assets/3997058/15507460/fee8780c-21cb-11e6-9ea3-b4eed697e029.png">

**Comment by matys18** [comment]
git push origin HEAD --force

 ;)
