### ISSUE TITLE
Menu Graphics

### ISSUE THREAD

**Issue by Jarlius** [matys18/Inda-project#43]
You mentioned making an animation earlier - are your hands full making an executable gamefile, or will that be ready?

Otherwise we could just use a picture of the yellowblob, and some descriptive text of the goal. For example: "This is blob. Help him find his friend again." or something along those lines

**Comment by Jarlius** [comment]
Haha oops, apparently you can't have two assignees :sob:

**Comment by matys18** [comment]
I'll have it done before tomorrows övning :thumbsup:

**Comment by Jarlius** [comment]
Great! :+1:

**Comment by matys18** [comment]
Just a blob, no text. No time.
