### ISSUE TITLE
Warning! Here be dragons!

### ISSUE THREAD

**Issue by macaullyjames** [matys18/Inda-project#8]
It looks like you're planning on using vanilla Java for this. Please don't! You'll get a lot more done and have a lot more fun if you use an actual game development framework. I say this because that teaser graphic looks super cool and I _really_ want to play this game, but if you're planning on using JFrames that's almost certainly not going to happen. 

These things:
- Smooth camera panning
- Smooth zooming in/out
- Cool lighting effects (like in the teaser image)
- Collision detection for non-rectangular walls (like in the teaser image)
- Sprite rendering
- Maintaining a steady frame rate
- And so on...

Take an enormous amount of time to implement correctly. It's not that I think you don't have the skills to do all that (you almost certainly do) but you're putting yourselves in a situation where there's a big risk of you not having a finished project after these three weeks. Even if you do manage to make some kind of game, it probably won't be the game you wanted to make. _Please, for your own sakes, use a framework._ [libGDX](https://libgdx.badlogicgames.com) seems to be what all the cool kids are using, but you can choose whatever you want to work with of course.

**Comment by matys18** [comment]
Dragons have been tamed (or so I hope)

**Comment by macaullyjames** [comment]
Fus!

**Comment by matys18** [comment]
Rho!

**Comment by Jarlius** [comment]
Dah!
